version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: carrybot-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  backend:
    image: haejih/carrybot-backend:latest
    container_name: carrybot-backend
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      PERPLEXITY_API_URL: ${PERPLEXITY_API_URL}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY}
      MQTT_BROKER: ${MQTT_BROKER}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID}
      MQTT_TOPIC: ${MQTT_TOPIC}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_REGION: ${S3_REGION}
      SMS_API_KEY: ${SMS_API_KEY}
      SMS_API_SECRET: ${SMS_API_SECRET}
      SMS_SENDER_NUMBER: ${SMS_SENDER_NUMBER}
      BITLY_TOKEN: ${BITLY_TOKEN}

  frontend:
    image: haejih/carrybot-frontend:latest
    container_name: carrybot-frontend
    restart: always
    ports:
      - "3000:80"

volumes:
  mysql-data:
