spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrybot?serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cors:
    allowed-origins: "http://localhost:3000" # 로컬 프론트 주소
server:
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs  # Swagger API Docs를 제공하는 URL 경로
  swagger-ui:
    path: /swagger-ui/index.html  # 기본 경로 사용

#springdoc:
#  api-docs:
#    path: /v3/api-docs  # Swagger API Docs를 제공하는 URL 경로
#  swagger-ui:
#    path: /swagger-ui.html  # Swagger UI의 경로


logging:
  level:
    root: debug

coolsms:
  api:
    api_key: ${SMS_API_KEY}
    api_secret: ${SMS_API_SECRET}
  sender:
    number: ${SMS_SENDER_NUMBER}
    url: jdbc:mysql://localhost:3306/carrybot?serverTimezone=Asia/Seoul
