spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}?serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Seoul
  cors:
    allowed-origins: "https://j12e104.p.ssafy.io"

server:
  servlet:
    context-path: /api

perplexity:
  api:
    url: ${PERPLEXITY_API_URL}
    key: ${PERPLEXITY_API_KEY}

mqtt:
  broker: ${MQTT_BROKER}
  username: ${MQTT_USERNAME}
  password: ${MQTT_PASSWORD}
  client-id: ${MQTT_CLIENT_ID}
  topic: ${MQTT_TOPIC}

logging:
  level:
    root: info

# ✅ develop에서 추가된 설정 ⬇️

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

coolsms:
  api:
    api_key: ${SMS_API_KEY}
    api_secret: ${SMS_API_SECRET}
  sender:
    number: ${SMS_SENDER_NUMBER}

bitly:
  api:
    token: ${BITLY_TOKEN}
